name = "presensi"
compatibility_date = "2023-10-01"

[[d1_databases]]
binding = "DB" # Nama binding yang akan digunakan di Worker
database_name = "presensi"
database_id = "7450f11c-34bf-4400-b591-d360fb1ea07e"